post:
    pattern:  /
    defaults: { _controller: "BearwolfBlogBundle:Post:index" }

post_show:
    pattern:  /{id}/show
    defaults: { _controller: "BearwolfBlogBundle:Post:show" }

post_new:
    pattern:  /new
    defaults: { _controller: "BearwolfBlogBundle:Post:new" }

post_create:
    pattern:  /create
    defaults: { _controller: "BearwolfBlogBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BearwolfBlogBundle:Post:edit" }

post_update:
    pattern:  /{id}/update
    defaults: { _controller: "BearwolfBlogBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BearwolfBlogBundle:Post:delete" }
    requirements: { _method: post|delete }

post_admin:
    pattern: /admin
    defaults: { _controller: "BearwolfBlogBundle:Post:admin" }